version: '3'

services:
  mysql:
     image: 'mysql:5.7'
     env_file:
        - ./.gitsecret/secrets/gasolinea.env
     volumes:
        - ./mysql/db:/var/lib/mysql
        - ./mysql/scripts:/docker-entrypoint-initdb.d
  site:
     build: './site'
     env_file:
        - ./.gitsecret/secrets/gasolinea.env
